### ISSUE TITLE
Don't die on missing resources

### ISSUE THREAD

**Issue by CrevsDaak** [CrevsDaak/m7multikit#17]
Currently, if a Scroll references a spell, and that spell is missing, installation will fail. Add a simple sanity check before the spell is copied. Not exactly a priority issue because it only happens if there are errors in other mods.

**Comment by Ineth2** [comment]
I encountered this issue with a broken scroll item from the TDDz mod.
Adding an `IF_EXISTS` to `m7multikit.tp2` fixes it.

Patch:

```
--- m7multikit/m7multikit.tp2	2019-07-22
+++ m7multikit/m7multikit.tp2	2020-04-16
@@ -193,6 +193,7 @@
 						PATCH_PRINT @1300035
 				END
 			END
+			IF_EXISTS
 			BUT_ONLY_IF_IT_CHANGES
 	END
```

...though even better than silently ignoring the item, would be to print a warning.
