### ISSUE TITLE
Can't find .exe file in the downloaded zip file

### ISSUE THREAD

**Issue by Jamie-jeminpark** [CrevsDaak/m7multikit#18]
Hi, I am really looking forward to playing BG EET with this incredible mod!

But, somewhat weirdly, I couldn't find any executable file in the downloaded zip file.

Thought it had to do with Vaccine software, I shut them down but couldn't find any still far.

Would you help me out with this issue?

**Comment by CrevsDaak** [comment]
Copy and rename any executable found in other mods to setup-m7multikit.exe
Alternatively you can download WeiDU from http://weidu.org/~thebigg/

I suppose I should mention the lack of a readily available WeiDU executable in the readme.
